[target.x86_64-pc-windows-msvc]
linker = "lld-link-14"
rustflags = [
  "-Lnative=/home/aruff/.xwin/crt/lib/x86_64",
  "-Lnative=/home/aruff/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/home/aruff/.xwin/sdk/lib/ucrt/x86_64"
]